---

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  # Prevent giant files from being committed.
  - id: check-added-large-files
  # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
  - id: check-case-conflict
  - id: detect-private-key

  # Check Markdown documents with Markdownlint(Node.js variant)
  # https://github.com/DavidAnson/markdownlint
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.23.2
  hooks:
  - id: markdownlint

  # Check YAML files
  # https://github.com/adrienverge/yamllint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.1
  hooks:
  - id: yamllint

- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.0
  hooks:
  - id: python-safety-dependencies-check
